name: weather_app
description: Weather Application

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^8.1.0
  provider: ^6.0.5
  http: ^0.13.5
  path_provider: ^2.0.11
  sqflite_sqlcipher: ^2.1.1+1
  path: ^1.8.2
  objectbox: ^1.7.1
  objectbox_flutter_libs: any
  geolocator: ^9.0.2
  location: ^5.0.0-dev.8
  permission_handler: ^10.2.0
  flutter_svg: 1.1.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_hooks: ^0.18.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mainIcons/
    - assets/cities/
